### ISSUE TITLE
二步验证无法开启

### ISSUE THREAD

**Issue by cdsjsz** [huoxue1/qinglong-go#2]
会一直卡白屏，看了下log
![image](https://user-images.githubusercontent.com/112803727/233757853-b5bbced9-ab54-46a5-83ce-c50af8b29f6e.png)
此外，dgrijalva/jwt-go存在着安全漏洞，可以更换为golang-jwt/jwt，这里稍微改下就行

![image](https://user-images.githubusercontent.com/112803727/233757988-3d119538-0152-48bb-aee8-761439e7e2fd.png)
![image](https://user-images.githubusercontent.com/112803727/233757999-808cc77b-cf9d-4347-9e91-89ff16d97333.png)

**Comment by huoxue1** [comment]
2be0e97682f6f702677f353c0dd26fc46bca2b9e
